name: Node - SSH deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  SFTP-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 🔨 Build Project
        run: |
          yarn
          yarn build

      - name: 📂 Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          # ARGS: "-rltgoDzvO --delete"
          SOURCE: 'build/'
          REMOTE_HOST: 192.34.62.123
          REMOTE_USER: mantis
          TARGET: public_html/free
          EXCLUDE_DIRS: '/dist/, /node_modules/'

